---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:5050/c/exchanges/api/ncmec
    body:
      encoding: UTF-8
      string: '{"credential_json":{"user":"user","password":"password"}}'
    headers:
      User-Agent:
      - Faraday v2.13.1
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Werkzeug/3.1.3 Python/3.11.12
      Date:
      - Wed, 04 Jun 2025 08:41:09 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '76'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {
          "has_set_authentification": true,
          "supports_authentification": true
        }
  recorded_at: Wed, 04 Jun 2025 08:41:09 GMT
recorded_with: VCR 6.3.1
